apiVersion: v1
kind: Secret
metadata:
  name: secret-app
  annotations:
    k8spatterns.io/podDeleteSelector: "app=secret-app"
data:
  VERSION: c2VjcmV0X3Zlcl8yLjE=
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secret-app
spec:
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: secret-app
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: secret-app
