apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
  namespace: elastic
spec:
  secretName: kibana-cert
  commonName: kibana.elastic.svc
  dnsNames:
    - kibana
    - kibana.elastic
    - kibana.elastic.svc
    - kibana.duongdx.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
