- name: Setup load balancers
  hosts: haproxy
  become: yes
  vars:
    master1: 192.168.56.11
    master2: 192.168.56.12
    master3: 192.168.56.13
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure haproxy
      template:
        src: "./haproxy/haproxy.cfg.j2"
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart haproxy

  handlers:
    - name: Restart haproxy
      systemd:
        name: haproxy
        state: restarted
        enabled: yes
        daemon-reload: yes