apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Default</title>
    </head>
    <body>
      <h1>Ingress Nginx work!</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: landing-page
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        resources:
          limits:
             memory: 100Mi
             cpu: 100m
          requests:
            memory: 100Mi
            cpu: 100m
      volumes:
      - name: landing-page
        configMap:
          name: landing-page
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30811
  selector:
    app: landing-page

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: ingress-test.duongdx.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: landing-page
            port:
              number: 80
